# Generated by Django 4.1.2 on 2022-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_sobre_urlvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '5.1) Contatos',
            },
        ),
        migrations.AlterModelOptions(
            name='dataevento',
            options={'verbose_name_plural': '1.3) Data do Contador'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': '2.1) Eventos'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': '2.2) Galeria de Imagens'},
        ),
        migrations.AlterModelOptions(
            name='inscricaodetalhe',
            options={'verbose_name_plural': '4.1) Inscrições (Página)'},
        ),
        migrations.AlterModelOptions(
            name='inscricaoitem',
            options={'verbose_name_plural': '4.2) Inscrições (Itens)'},
        ),
        migrations.AlterModelOptions(
            name='patrocinio',
            options={'verbose_name_plural': '1.4) Patrocinios'},
        ),
        migrations.AlterModelOptions(
            name='regulamentodetalhe',
            options={'verbose_name_plural': '3.1) Regulamentos (Página)'},
        ),
        migrations.AlterModelOptions(
            name='regulamentoitem',
            options={'verbose_name_plural': '3.2) Regulamentos (Itens)'},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={'verbose_name_plural': '1.2) Sliders'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name_plural': '1.1) Sobre (Página)'},
        ),
    ]
